DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Tulos CASCADE;
DROP TABLE IF EXISTS Sarja CASCADE;
DROP TABLE IF EXISTS Aselaji CASCADE;
DROP TABLE IF EXISTS Kilpailumuoto CASCADE;
DROP TABLE IF EXISTS KilpailumuodonLaji CASCADE;